language: php
sudo: false

notifications:
  email: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

php:
  - 7.3
  - 7.2
  - 7.1
  - 7.0

env:
  - WP_VERSION=latest
  - WP_VERSION=4.9.9

matrix:
  fast_finish: true
  include:
    - name: Coding Standards
      php: 7.2
      env: WP_VERSION=latest RUN_PHPCS=1
    - name: Code Coverage
      php: 7.2
      env: WP_VERSION=latest RUN_CODE_COVERAGE=1
    - name: Bleeding Edge
      php: 7.3
      env: WP_VERSION=trunk
  exclude:
    # WordPress < 5.0 doesn't officially support PHP 7.3
    - php: 7.3
      env: WP_VERSION=4.9.9
  allow_failures:
    - name: Code Coverage
      php: 7.2
      env: WP_VERSION=latest RUN_CODE_COVERAGE=1
    - name: Bleeding Edge
      php: 7.3
      env: WP_VERSION=trunk

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - composer install --prefer-dist
  - bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - |
    if [[ ${RUN_CODE_COVERAGE} ]]; then
      wget https://github.com/php-coveralls/php-coveralls/releases/download/v1.0.0/coveralls.phar
      chmod +x coveralls.phar
      mkdir -p build/logs
    fi

script:
  - |
    if [[ ${RUN_PHPCS} == 1 ]]; then
      ./vendor/bin/phpcs
    elif [[ ${RUN_CODE_COVERAGE} ]]; then
      phpdbg -qrr -d memory_limit=-1 ./vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=build/logs/clover.xml --exclude-group=timeout
    else
      WP_MULTISITE=0 ./vendor/bin/phpunit
      WP_MULTISITE=1 ./vendor/bin/phpunit
    fi

after_success:
  - |
    if [[ ${RUN_CODE_COVERAGE} ]]; then
      travis_retry php coveralls.phar
    fi
