language: php
sudo: false

notifications:
  email: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

php:
  - 7.3
  - 7.2
  - 7.1
  - 7.0

env:
  - WP_VERSION=latest

matrix:
  fast_finish: true
  include:
    - name: Coding Standards
      php: 7.2
      env: WP_VERSION=latest RUN_PHPCS=1
    - name: Bleeding Edge
      php: 7.3
      env: WP_VERSION=trunk

before_install:
  - phpenv config-rm xdebug.ini

install:
  - composer install --prefer-dist
  - bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - mkdir -p build/logs

script:
  - WP_MULTISITE=0 ./vendor/bin/phpunit
  - WP_MULTISITE=1 ./vendor/bin/phpunit
  - |
    if [[ ${RUN_PHPCS} == 1 ]]; then
      ./vendor/bin/phpcs
    fi
  - ./vendor/bin/test-reporter
